apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeclusters.demo.upbound.io
  labels:
    idp: "true"
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Cluster Info
        description: Information about this cluster.
        items:
        - name: id
          controlType: singleInput
          type: string
          path: ".spec.id"
          title: Cluster ID
          description: Cluster ID that other objects will use to refer to this cluster.
          default: my-cool-cluster
          validation:
          - required: true
            customError: Cluster ID is required.
        - name: writeSecretRef
          controlType: singleInput
          type: string
          path: ".spec.writeConnectionSecretToRef.name"
          title: Connection Secret Reference
          description: Name of the secret to write to this namespace.
          default: my-cool-cluster-conn
          validation:
          - required: true
      - title: Cluster Config
        description: Configuration for this cluster.
        items:
        - name: version
          controlType: singleInput
          type: string
          path: ".spec.parameters.version"
          title: Version
          description: The Kubernetes version for this cluster.
          validation:
          - required: true
            customError: Version is required.
        - name: nodeSize
          controlType: singleSelect
          type: string
          path: ".spec.parameters.nodeSize"
          title: Size
          description: Supported sizes are small, medium, and large.
          default: small
          enum:
          - small
          - medium
          - large
          validation:
          - required: false
        - name: minNodeCount
          controlType: singleInput
          type: string
          path: ".spec.parameters.minNodeCount"
          title: Minimum Node Count
          description: Minimum number of nodes in the cluster.
          default: 1
          validation:
          - required: false
spec:
  connectionSecretKeys:
  - kubeconfig
  - value
  defaultCompositionRef:
    name: cluster-aws
  group: demo.upbound.io
  names:
    kind: CompositeCluster
    plural: compositeclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects can refer.
              parameters:
                type: object
                description: Parameters used to customize the cluster
                properties:
                  version:
                    description: The Kubernetes version for the cluster.
                    type: string
                  nodeSize:
                    description: The size of the nodes; small, medium, large.
                    type: string
                  minNodeCount:
                    description: The minimum number of nodes.
                    type: integer
                    default: 1
                required:
                - nodeSize
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The name of the cluster.
                type: string
              controlPlaneStatus:
                description: The status of the control plane.
                type: string
              nodePoolStatus:
                description: The status of the node pool.
                type: string
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: ".status.clusterName"
    - name: controlPlane
      type: string
      jsonPath: ".status.controlPlaneStatus"
    - name: nodePool
      type: string
      jsonPath: ".status.nodePoolStatus"
