
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upbound-infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: upbound
  source:
    repoURL: https://github.com/upbound/demos.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://proxy.upbound.io/controlPlanes/da93e2e2-21cf-4666-8130-65b4a60f53f2
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true