---

apiVersion: upbound.io/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo-app
spec:
  id: silly-demo-app
  compositionSelector:
    matchLabels:
      type: backend-db
      location: remote
  parameters:
    namespace: production
    image: vfarcic/sql-demo:0.1.10
    port: 8080
    host: acme.com
    kubernetesProviderConfigName: a-team-eks
    dbSecret:
      name: silly-demo-db
      namespace: upbound-system

---

apiVersion: upbound.io/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo-db
spec:
  id: silly-demo-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13.4"
    size: small
  writeConnectionSecretToRef:
    name: silly-demo-db
    namespace: upbound-system
